### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by tomaszewski525** [WojciechSzade/secure-lending-system#1]
Hello,
I will speak Polish... Zainstalowałem Pana aplikację. Po jej skonfigurowaniu zniknęły mi wszystkie środki z konta. Czy mógłby Pan mi powiedzieć gdzie są moje pieniądze? Chłopaki z Legnicy na pewno ich nie mają. Now English
Best regards,
Paruwa Denta

**Comment by WojciechSzade** [comment]
Hello Dear Tomasz,
please read the readme.md file ans contributing notes and repost your issue following the provided format.
Thank you,
Wojciech Szade
